# Generated by Django 3.1.14 on 2025-06-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendshiprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='id_approved',
            new_name='is_approved',
        ),
    ]
